# This follow defines various global variables to use throughout the site.
# You can access them using Liquid like: `{{site.dart-api}}`.

title: Dart
description: >-
  Dart is a client-optimized language for developing fast apps on any platform.
url: https://dart.cn
redirect:
  go: https://dart.dev/go
repo:
  this: https://github.com/cfug/dart.cn
  shared: https://github.com/dart-lang/site-shared
  dart:
    org: https://github.com/dart-lang
    sdk: https://github.com/dart-lang/sdk
    lang: https://github.com/dart-lang/language
branch: main

flutter: https://flutter.cn
flutter-docs: https://docs.flutter.cn
dart-api: https://api.dart.cn
flutter-api: https://api.flutter-io.cn
pub: https://pub-web.flutter-io.cn
pub-api: https://pub-web.flutter-io.cn/documentation
pub-pkg: https://pub-web.flutter-io.cn/packages
dartpad: https://dartpad.cn
news: https://news.dartlang.org
announce: https://groups.google.com/a/dartlang.org/g/announce
android-dev: https://developer.android.com
apple-dev: https://developer.apple.com

yt:
  watch: 'https://www.youtube.com/watch'
  playlist: 'https://www.youtube.com/playlist?list='

# dart.cn - bilibili.com
bili:
  set: 'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen loading="lazy"'
  set-short: 'frameborder="0" allowfullscreen loading="lazy"'
  video: 'https://www.bilibili.com/video'
  embed: 'https://player.bilibili.com/player.html'
  std-size: 'width="560" height="315"'

showBanner: true

# Increment this global og:image URL version number (used as a query parameter)
# when you update any og:image file. (Also increment the corresponding number
# in the `firebase.json` redirect rule.)
og_image_vers: "?2"

sdkVersion: 3.7.2
