name: Markdown links reference check

on: [push, pull_request]

env:
  NODE_ENV: production
  NODE_VERSION: 15

jobs:
  check_reference_links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - run: mkdir -p ${{ github.workspace }}/tmp
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ruby/setup-ruby@v1
        if: contains(matrix.task, 'build.sh')
        with:
          bundler-cache: true
          ruby-version: 2.6.5
      - uses: dart-lang/setup-dart@v1.2
        with:
          sdk: stable
      - name: Install node dependencies
        # TODO: caching requires a lockfile for node deps, so does npm ci.
        run: npm install
      - name: Install dart dependencies
        run: dart pub get
      - run: ./tool/shared/write-ci-info.sh -v
      - name: Build
        run: ./tool/build.sh

      # check
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - run: python tool/html_check_reference_links.py _site https://dart.cn/
